### ISSUE TITLE
fails to build with QuichCheck 2.16

### ISSUE THREAD

**Issue by juhp** [0xd34df00d/binary-generic-combinators#3]
For Stackage Nightly:

```
       Building library for binary-generic-combinators-0.4.4.0...                                               03:47:21 [85/909229]
       [1 of 3] Compiling Data.Binary.Combinators                                                                                   
       /home/curators/work/unpack-dir/unpacked/binary-generic-combinators-0.4.4.0-16db337c3aa8a95967f007060b229168e510e16625352ac1bb
a028db92cd91ea/src/Data/Binary/Combinators.hs:77:26: error: [GHC-87543]                                                             
           Ambiguous occurrence ‘Some’.                                                                                             
           It could refer to                                                                                                        
              either ‘Test.QuickCheck.Some’,
                     imported from ‘Test.QuickCheck’ at src/Data/Binary/Combinators.hs:52:1-22
                     (and originally defined in ‘Test.QuickCheck.Monoids’),
                  or ‘Data.Binary.Combinators.Some’,
                     defined at src/Data/Binary/Combinators.hs:75:1.
          |
       77 | instance Show a => Show (Some a) where
          |                          ^^^^
        
       /home/curators/work/unpack-dir/unpacked/binary-generic-combinators-0.4.4.0-16db337c3aa8a95967f007060b229168e510e16625352ac1bb
a028db92cd91ea/src/Data/Binary/Combinators.hs:78:17: error: [GHC-87543]
           Ambiguous occurrence ‘getSome’.
           It could refer to
              either the field ‘getSome’ of record ‘Test.QuickCheck.Some’,
                     imported from ‘Test.QuickCheck’ at src/Data/Binary/Combinators.hs:52:1-22
                     (and originally defined in ‘Test.QuickCheck.Monoids’),
                  or the field ‘getSome’ of record ‘Data.Binary.Combinators.Some’,
                     defined at src/Data/Binary/Combinators.hs:75:25.
          |
       78 |   show = show . getSome
          |                 ^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/binary-generic-combinators-0.4.4.0-16db337c3aa8a95967f007060b229168e510e16625352ac1bb
a028db92cd91ea/src/Data/Binary/Combinators.hs:80:30: error: [GHC-87543]
           Ambiguous occurrence ‘Some’.
           It could refer to
              either ‘Test.QuickCheck.Some’,
                     imported from ‘Test.QuickCheck’ at src/Data/Binary/Combinators.hs:52:1-22
                     (and originally defined in ‘Test.QuickCheck.Monoids’),
                  or ‘Data.Binary.Combinators.Some’,
                     defined at src/Data/Binary/Combinators.hs:75:1.
          |
       80 | instance Binary a => Binary (Some a) where
          |                              ^^^^
```

**Comment by 0xd34df00d** [comment]
@juhp should be good now, builds for me locally with quickcheck-2.16. Is there any way for me to help test this in stackage nightly?

**Comment by juhp** [comment]
Well you can try to build with the just published https://www.stackage.org/nightly-2025-07-19

Anyway if you believe it is fixed now you can just open a PR to revert the above change or I can also do it if you want.

**Comment by juhp** [comment]
You may also want to check the testsuite, which was already disabled in Nightly.
